# Generated by Django 4.0.5 on 2022-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(default='', max_length=20)),
                ('message', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnm', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stafffn', models.CharField(default='', max_length=20)),
                ('staffln', models.CharField(default='', max_length=20)),
                ('staffsub', models.CharField(default='', max_length=20)),
                ('staffstd', models.CharField(default='', max_length=20)),
                ('staffcity', models.CharField(default='', max_length=20)),
                ('staffphoto', models.FileField(default='', upload_to='staffimag')),
                ('phno', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=20)),
                ('experience', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(default='', max_length=20)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('ststd', models.CharField(default='', max_length=20)),
                ('stcity', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('enrno', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('stphoto', models.FileField(default='', upload_to='photoupload')),
            ],
        ),
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('role', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
