# Generated by Django 4.0.6 on 2022-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_staff_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
